package cz.petrchatrny.tennisclub.service.smsservice;

/**
 * Service for sending SMS messages to user's phone numbers.
 */
public interface ISmsService {
    /**
     * Sends info message about created reservation and registration in system.
     * Shows autogenerated password to user.
     *
     * @param phoneNumber user's phone number
     * @param password    user's password generated by system
     */
    void sendRegistrationMessage(String phoneNumber, String password);
}
